import type { SiteData } from '../types/content';

// All portfolio content lives here. Update this file to customize the site.
// Synced with master_resume_2026-10-01/master_resume.pdf (refreshed 2026-10-01).
export const siteData: SiteData = {
  name: 'Thinh Tran',
  role: 'Full-Stack Developer · CS Student',
  location: 'Toronto, Ontario, Canada',
  heroTagline:
    'Shipping production-grade software end-to-end — from REST APIs and security hardening to e-learning, analytics and AI-agent automation.',
  heroIntro:
    'Computer Science co-op student at York University (expected 2027), currently a Learning Technology & AI Enablement Intern at Groupe Bel Canada. I ship production web apps, AI-agent automation, e-learning technology and analytics for real organizations — with a bias toward shipping, testing, and work that holds up under real users.',
  heroHighlights: [
    {
      label: 'Currently',
      items: [
        'Learning Technology & AI Enablement Intern · Groupe Bel Canada',
        'B.A. Computer Science (Honours), Co-op · York University · Sep 2024 – Expected 2027',
        'Available for Summer 2027 co-op',
      ],
    },
    {
      label: 'Stacks I reach for',
      items: [
        'Next.js · React 18/19 · TypeScript',
        'FastAPI · Spring Boot · Node.js',
        'PostgreSQL · MongoDB · Prisma · Redis',
      ],
    },
    {
      label: 'Currently learning',
      items: ['Distributed systems', 'WebGL / Canvas graphics', 'Quant finance & ML for time-series'],
    },
    {
      label: 'Off the keyboard',
      items: ['Basketball', 'Volleyball', 'Rock climbing', 'Weightlifting', 'Cooking', 'EN · FR · VI'],
    },
  ],
  about: {
    paragraphs: [
      "I'm a B.A. Computer Science (Honours) co-op student at York University, expected to graduate in 2027, focused on full-stack engineering, analytics, and AI-agent automation. I care about code that ships — well-tested, observable, and pleasant to work in six months from now.",
      "Right now I'm a Learning Technology & AI Enablement Intern at Groupe Bel Canada, building SCORM e-learning for the company's learning platform and a weekly-refreshed Power BI learning-engagement report the team uses. Over the summer I owned the Florida-expansion web workstream at Swimingo through Riipen Labs, and I'm the on-call developer for Pho Ginger, my family's Vietnamese restaurant, and its live ordering platform.",
      'My own projects span full-stack web (Next.js + FastAPI), portfolio analytics (Python + NumPy + Recharts), mobile (React Native + Expo), embedded firmware (ESP32-C3 in C + RISC-V Assembly), and Java coursework. I prefer building the boring scaffolding (rate limits, security headers, TTL cleanup crons, fallback chains) over chasing what is trendy, and I build with Claude Code agent teams: I design and direct the work, and separate validator agents check it before it ships.',
      'I think design and engineering should not be separated. Every web project I ship has a deliberate visual language, a typography scale, and motion that respects physics. I treat the UI layer with the same rigor as the backend.',
    ],
  },
  skills: {
    languages: [
      'TypeScript',
      'JavaScript',
      'Python',
      'Java',
      'C / C++',
      'C# (Basic)',
      'SQL',
      'DAX',
      'HTML / CSS',
    ],
    frameworks: [
      'Next.js 16 (App Router)',
      'React 18 / 19',
      'React Native (Expo SDK 54)',
      'FastAPI',
      'Spring Boot · Spring Data JPA',
      'Node.js',
      'Tailwind CSS',
      'Framer Motion',
      'Redux Toolkit',
      'Recharts · NumPy · Pandas',
      'Prisma 6 · SQLAlchemy 2.0 · Alembic',
      'React Hook Form · Zod · Pydantic v2',
      'Playwright · Vitest · Pytest · JUnit',
      'JavaFX',
      'Zustand · Gradle · Upstash Ratelimit · Resend',
    ],
    tools: [
      'Git · GitHub · GitHub Actions',
      'Docker · Linux / CLI · ESLint',
      'Vercel · Koyeb · Neon · Netlify',
      'Expo / EAS · Chrome Manifest V3',
      'Claude Code agent orchestration · MCP · Microsoft Copilot',
      'Power BI (DAX, Power Query)',
      'SCORM 2004 / 1.2 · SCORM Cloud · LMS administration',
      'Google Search Console · JSON-LD / Schema.org · sitemaps',
      'Microsoft 365 (Excel, PowerPoint, Word, SharePoint) · Adobe Premiere Pro',
      'PostgreSQL · MongoDB · Redis / Upstash · SQLite',
      'MySQL · Microsoft SQL Server · Azure SQL / Cosmos DB',
      'FreeRTOS on ESP32-C3',
    ],
  },
  experience: [
    {
      id: 'exp-yorku',
      role: 'B.A. Computer Science (Honours), Co-op',
      company: 'York University',
      location: 'Toronto, Ontario',
      start: 'Sep 2024',
      end: 'Expected 2027',
      description:
        'Co-op program; first work term at Groupe Bel Canada, Fall 2026. Relevant coursework: Data Structures & Algorithms, Computer Organization (A+), Database Systems, Software Design (UML, requirements, SDLC), Professional Practice in Computing (A), Software Tools. Prior study: Western University (2021–2024), including a year of media studies with hands-on Adobe Premiere Pro coursework.',
    },
    {
      id: 'exp-bel',
      role: 'Learning Technology & AI Enablement Intern',
      company: 'Groupe Bel Canada',
      location: 'Mississauga, Ontario (Hybrid)',
      start: 'Jul 2026',
      end: 'Present',
      description:
        "Orchestrated Claude Code agent teams with independent validators to build 30+ SCORM e-learning packages for the company's global learning academy, including 18 capability courses now live on the corporate LMS. Fixed a quiz-export defect that marked low scorers \"failed\" and kept them from completing a learning pathway: traced it in the package, rewrote its LMS reporting for SCORM 2004 so a below-pass attempt stays open for retry, and proved both paths on a real SCORM engine. Restored full learner tracking after finding that replacement quizzes sent the LMS less data than the packages they replaced. Built and maintain a Power BI report (10 pages, 72 DAX measures) tracking learning engagement for a 1,769-person community across ~18,000 activity records, used by the team and refreshed weekly, after auditing the LMS export and catching a sign-in total inflated 35×. Building a two-hour, demo-led Microsoft Copilot workshop for the team (delivering Oct 19, 2026), and rebuilt 2.4 hours of recorded system-training webinars into an 8-module narrated, subtitled video series (release pending).",
    },
    {
      id: 'exp-swimingo',
      role: 'SEO & Web Developer',
      company: 'Swimingo (via Riipen Labs)',
      location: 'Remote',
      start: 'Jul 2026',
      end: 'Sep 2026',
      description:
        "Owned the Florida-expansion web workstream end to end, shipping 14 Florida pages (a hub, 11 town pages and 2 instructor-recruitment pages, live at swimingo.com/swim-lessons/fl) into the company's React / TypeScript / Vite codebase across 6 merged pull requests: routing, prerendering, sitemaps, JSON-LD structured data, canonicals and a boundary-checked internal-linking mesh. Took the first six Florida pages from 0 to 310 Google search impressions, with Cooper City on page one (average position 8.6) about five weeks after launch. Diagnosed a wrong-address indexing leak (17.5% of impressions at baseline, 6.9% by the end) and added build gates that require a unique title, description and single canonical on every public route and fail the build on unsupported claims or bad structured data, each proven by injecting the fault it guards against.",
    },
    {
      id: 'exp-upnxxt',
      role: 'Technical Lead',
      company: 'UpNxxt (via Riipen Labs)',
      location: 'Remote',
      start: 'Jun 2026',
      end: 'Jun 2026',
      description:
        "Operations / Technical Lead on a 5-person team in a three-week sprint for an edtech startup teaching AI literacy to children. Authored Playwright browser-automation scripts to walk the product's signup and lesson flow as a real user, scraping the DOM to measure on-screen word count as a proxy for drop-off risk. Identified the first one or two lessons as the highest-leverage friction point and recommended an interactive, age-segmented redesign grounded in UNESCO, Nielsen Norman Group and cognitive-load research. Delivered a 17-slide customer-experience optimization report, owning 5 slides and generating the deck with python-pptx so it rebuilt after every edit.",
    },
    {
      id: 'exp-pho-ginger',
      role: 'Full Stack Developer (On Call)',
      company: 'Pho Ginger',
      location: 'Toronto, Ontario',
      start: 'Mar 2026',
      end: 'Present',
      description:
        'Built and maintain a production ordering platform serving about 50 customers a day, as sole developer orchestrating Claude Code agents: customer storefront and private staff tablet dashboard in Next.js 16, TypeScript, React 19, Tailwind v4, MongoDB Atlas, Prisma 6 and Vercel. Developed 13 typed REST API routes with Zod validation and server-side recomputation of every order total, eliminating client-side price tampering. Hardened the platform with HMAC-SHA256 signed HttpOnly session cookies, Upstash Redis sliding-window rate limits on 5 endpoints, CSRF origin checks and HSTS / security headers; cleared ~19 security advisories in a July 2026 dependency upgrade. Shipped owner-editable menu management (sold-out toggles, price overrides, photo uploads) and a background new-order alarm (desktop) the owner accepted in testing; a 22-test Playwright end-to-end suite checks that menu edits reach the storefront and sold-out orders are rejected.',
    },
    {
      id: 'exp-aritzia',
      role: 'Inventory Management Associate',
      company: 'Aritzia Distribution Center',
      location: 'Vaughan, Ontario',
      start: 'Apr 2025',
      end: 'Aug 2026',
      description:
        'Managed real-time inventory tracking, SKU accuracy and stock reconciliation in a high-volume distribution environment using warehouse management systems (WMS) and barcode scanning. Maintained data integrity through cycle counting, variance reporting, quality checks and Excel/CSV reporting, scaling inventory processes as volume increased.',
    },
  ],
  projects: [
    {
      id: 'proj-ginger',
      title: 'Pho Ginger — Pickup Ordering Platform',
      tagline: 'Real Vietnamese restaurant. Real customers. Real orders.',
      description:
        'A mobile-first Next.js 16 ordering site running in production for my family\'s Vietnamese restaurant in Toronto. Customers browse, customize, and place pay-in-person pickup orders; staff run orders, pause ordering and edit the menu from a private tablet dashboard. 13 typed REST API routes with Zod validation, server-side order-total recomputation (clients never send prices), HMAC-SHA256 signed HttpOnly session cookies, per-order 128-bit viewToken, Upstash Redis rate limits on 5 endpoints, CSRF checks on every state-changing request, a Vercel cron heartbeat to keep the Atlas free tier from auto-pausing, and a 22-test Playwright end-to-end suite.',
      tech: [
        'Next.js 16',
        'TypeScript',
        'React 19',
        'Tailwind CSS v4',
        'MongoDB Atlas',
        'Prisma 6',
        'Resend',
        'Upstash Redis',
        'Vercel',
        'Zod',
        'Playwright',
      ],
      links: [
        { label: 'Live site', href: 'https://gingercuisine.ca/' },
        { label: 'GitHub', href: 'https://github.com/tvtrvn/gingercuisine-app' },
      ],
      highlight:
        'Live in a real restaurant. Polling staff dashboard, background new-order alarm (desktop), pause-ordering control, full security model.',
      year: '2026',
      role: 'Sole engineer',
      status: 'live',
      kind: 'fullstack',
      featured: true,
      starred: true,
      metrics: [
        { label: 'Daily customers', value: '~50' },
        { label: 'REST routes', value: '13' },
        { label: 'Rate-limited endpoints', value: '5' },
      ],
    },
    {
      id: 'proj-portfolio-analytics',
      title: 'Portfolio Analytics Dashboard',
      tagline: 'Portfolio risk and performance analytics on simulated data — solo build.',
      description:
        'Full-stack portfolio analytics platform for 4 sample portfolios over 32 simulated securities, seeded with geometric Brownian motion. Built solo with React 18 + TypeScript + Redux Toolkit (4 slices) + Recharts (5 chart types) + Vite 5 on the frontend, Python 3.11 + FastAPI + SQLAlchemy 2.0 + Pydantic v2 on the backend. Designed an 8-table normalized PostgreSQL schema with 5 composite indexes and built 18 REST API endpoints serving portfolio summaries, holdings, performance series, attribution, risk metrics, and benchmark comparison. The analytics engine is pure NumPy — 11 financial metrics from first principles (Sharpe ratio, max drawdown, VaR / CVaR, tracking error, beta, annualized volatility).',
      tech: [
        'React 18',
        'TypeScript',
        'Redux Toolkit',
        'Recharts',
        'Vite 5',
        'Tailwind CSS',
        'Python 3.11',
        'FastAPI',
        'SQLAlchemy 2.0',
        'Pydantic v2',
        'NumPy',
        'PostgreSQL',
      ],
      links: [
        { label: 'GitHub', href: 'https://github.com/tvtrvn/portfolio-analytics-dashboard' },
      ],
      highlight:
        '4 sample portfolios · 32 simulated securities · 8-table schema, 5 composite indexes · 18 endpoints · 11 metrics from first principles.',
      year: '2026',
      role: 'Sole engineer',
      status: 'shipped',
      kind: 'fullstack',
      featured: true,
      metrics: [
        { label: 'API endpoints', value: '18' },
        { label: 'Financial metrics', value: '11' },
        { label: 'Simulated securities', value: '32' },
      ],
    },
    {
      id: 'proj-historical-trade-sim',
      title: 'Historical Trade Scenario Simulator',
      tagline: 'Replay lump-sum and DCA decisions on real price history since 2010.',
      description:
        'A trade simulator for lump-sum and dollar-cost-averaging scenarios across 12 stocks and ETFs with price history back to 2010, with benchmark overlays, drawdown chart, per-year return bars, and a full trade ledger. Built with Vite 5, React 18, TypeScript, Tailwind 3, Framer Motion 11, FastAPI, and PostgreSQL 16. Real prices come from Tiingo with a Yahoo Finance fallback (and a deterministic synthetic fallback as the last tier); defense-in-depth middleware adds per-IP rate limiting (120 req/min), a 64KB body cap, a 100 saved-scenarios cap, 30-day TTL cleanup, and a bearer-token-protected maintenance route. 76 passing tests across 4 suites (finance unit, security end-to-end, maintenance, market-data); a daily GitHub Actions cron handles price refresh + TTL cleanup; HSTS, X-Frame-Options, COOP/CORP, and `no-store` on all API routes.',
      tech: [
        'Vite 5',
        'React 18',
        'TypeScript',
        'Tailwind 3',
        'Framer Motion 11',
        'Recharts',
        'FastAPI',
        'Python 3.11',
        'SQLAlchemy 2.0',
        'Alembic',
        'PostgreSQL 16',
        'Neon',
        'Koyeb',
        'Vercel',
        'GitHub Actions',
      ],
      links: [
        { label: 'Live site', href: 'https://historical-trade-sim.vercel.app/' },
        { label: 'GitHub', href: 'https://github.com/tvtrvn/historical-trade-sim' },
      ],
      highlight:
        '76 tests passing · 12 stocks & ETFs since 2010 · Tiingo → Yahoo Finance fallback · daily TTL cleanup cron.',
      year: '2026',
      role: 'Designer + sole engineer',
      status: 'live',
      kind: 'fullstack',
      featured: true,
      metrics: [
        { label: 'Backend tests', value: '76' },
        { label: 'Stocks & ETFs', value: '12' },
        { label: 'Hardening controls', value: '7' },
      ],
    },
    {
      id: 'proj-fridgefit',
      title: 'FridgeFit — iOS & Android App',
      tagline: 'Flip the recipe app. Start with the fridge, end with dinner.',
      description:
        'Cross-platform recipe app built with Expo SDK 54, React Native 0.81, React 19, TypeScript, and Expo Router (file-based navigation). State managed via Zustand, local persistence via Expo SQLite, forms via React Hook Form + Zod. Add what is in your fridge and recipes from TheMealDB are ranked by ingredient match; open a recipe detail, save favorites, and set diet and allergen filters that persist. 6 of 8 milestones shipped — ingredient-match discovery, recipe detail, favorites, filters, and onboarding, with core flows tested on real devices. Not released yet: the meal-planner / nutrition milestone and App Store submission are still ahead.',
      tech: [
        'Expo SDK 54',
        'React Native 0.81',
        'React 19',
        'TypeScript',
        'Expo Router',
        'Zustand',
        'Expo SQLite',
        'React Hook Form',
        'Zod',
        'TheMealDB API',
        'EAS Build',
      ],
      links: [
        { label: 'GitHub', href: 'https://github.com/tvtrvn/FridgeFit-app' },
      ],
      highlight:
        '6 of 8 milestones shipped · local SQLite persistence · file-based routing · not yet on the App Store.',
      year: '2026',
      role: 'Designer + mobile engineer',
      status: 'in-progress',
      kind: 'mobile',
      featured: true,
    },
    {
      id: 'proj-youtube-vpop',
      title: 'Top 50 Vietnamese Pop Videos — YouTube Viewer',
      tagline: 'Daily-snapshot leaderboard of vpop on YouTube.',
      description:
        'Next.js 16 App Router app displaying the top 100 most-viewed long-form Vietnamese pop music videos on YouTube (25 per page). Integrates YouTube Data API v3 with two parallel search queries (English + Vietnamese), videos.list enrichment in batches of 50, and ISO 8601 duration filtering to strip Shorts. Implements a MongoDB daily-snapshot cache with a 30-day TTL index to auto-prune stale data; designed quota-aware API usage (~1010 YouTube units per cold load) to stay within the 10,000-unit free daily quota.',
      tech: ['Next.js 16', 'React 19', 'TypeScript', 'Tailwind CSS 4', 'MongoDB', 'YouTube Data API v3', 'Vercel'],
      links: [
        { label: 'Live site', href: 'https://first-repo-live.vercel.app/' },
        { label: 'GitHub', href: 'https://github.com/tvtrvn/first-repo-live' },
      ],
      highlight: '~1010 YouTube quota units / cold load · TTL-indexed snapshot cache.',
      year: '2025',
      role: 'Sole engineer',
      status: 'shipped',
      kind: 'fullstack',
    },
    {
      id: 'proj-procrastination',
      title: 'Anti-Procrastination Chrome Extension',
      tagline: 'Focus session, AFK nudge, site blocker — all in one MV3 extension.',
      description:
        'Manifest V3 Chrome extension in vanilla HTML / CSS / JavaScript. Blocks distracting sites via declarativeNetRequest dynamic rules and runs focus sessions with AFK idle detection (chrome.idle, 120 s threshold). Timer uses chrome.alarms for service-worker resilience; data persisted via chrome.storage.local. After 120 s AFK, opens a single nudge tab.',
      tech: [
        'JavaScript',
        'HTML',
        'CSS',
        'Chrome Manifest V3',
        'declarativeNetRequest',
        'chrome.alarms',
        'chrome.idle',
        'chrome.storage',
      ],
      links: [
        { label: 'GitHub', href: 'https://github.com/tvtrvn/chrome-extension-anti-procrastination' },
      ],
      highlight: 'Service worker–driven timer survives popup close · session capped at 3 hr.',
      year: '2025',
      role: 'Sole engineer',
      status: 'shipped',
      kind: 'extension',
    },
    {
      id: 'proj-connect-four',
      title: 'Connect Four — EECS3311 Software Design',
      tagline: 'MVC, Strategy, Factory, and Command patterns from the ground up.',
      description:
        'Team course project: a Java MVC game with separated model, view, and controller layers; applied Observer, Strategy, Factory, and Command design patterns for a maintainable, extensible architecture. Wrote JUnit unit and integration tests covering board rules, invalid moves, save / load, and undo / redo. Coordinated development using Git / GitHub, Trello, user stories, and Agile-style sprints.',
      tech: [
        'Java',
        'JavaFX',
        'JUnit',
        'MVC',
        'Observer Pattern',
        'Strategy Pattern',
        'Factory Pattern',
        'Command Pattern',
        'Git',
        'Trello',
      ],
      links: [
        { label: 'GitHub', href: 'https://github.com/tvtrvn/EECS3311-A2-ConnectFour' },
      ],
      highlight: 'Observer · Strategy · Factory · Command · JUnit tests for undo / redo and save / load.',
      year: '2025',
      role: 'Team course project',
      status: 'shipped',
      kind: 'systems',
    },
    {
      id: 'proj-esp32',
      title: 'ESP32-C3 Embedded LED Firmware',
      tagline: 'WS2812 LED firmware in C + RISC-V Assembly on FreeRTOS.',
      description:
        'Programmed firmware for an ESP32-C3 development board controlling WS2812 addressable LEDs in C and RISC-V Assembly with FreeRTOS. Handled hardware timing control and debugged the firmware on a physical development board.',
      tech: ['C', 'RISC-V Assembly', 'FreeRTOS', 'WS2812', 'ESP32-C3'],
      links: [],
      highlight: 'WS2812 timing control on real ESP32-C3 hardware.',
      year: '2025',
      role: 'Firmware developer',
      status: 'shipped',
      kind: 'systems',
    },
    {
      id: 'proj-portfolio',
      title: 'This Portfolio',
      tagline: 'Editorial-grade portfolio. Custom design system. No template.',
      description:
        'The site you are reading. Vite + React + TypeScript + Tailwind v3 with a hand-built design system: warm bone-on-charcoal palette, Fraunces + Geist + JetBrains Mono typography stack, custom cubic-bezier motion, animated canvas mesh-blob hero, magnetic CTAs, spotlight project cards, floating dock navbar, and a fixed grain overlay. Deployed on Netlify.',
      tech: ['Vite', 'React 18', 'TypeScript', 'Tailwind CSS 3', 'Framer Motion 11', 'Phosphor Icons', 'Netlify'],
      links: [
        { label: 'Live site', href: 'https://thinh-tran-portfoliosite.netlify.app/' },
        { label: 'GitHub', href: 'https://github.com/tvtrvn/portfolio_v' },
      ],
      highlight: 'Hand-built design system · animated canvas hero · custom motion choreography.',
      year: '2026',
      role: 'Designer + engineer',
      status: 'live',
      kind: 'frontend',
    },
  ],
  certifications: [
    {
      id: 'cert-design-patterns',
      title: 'Mastering Design Patterns with Java',
      issuer: 'CodeSignal',
      date: 'Apr 2026',
      verifyUrl: 'https://codesignal.com/learn/certificates/cmi5b4a3k003kjy04h90j6fip/course-paths/85',
      description:
        'Creational, Structural & Behavioral patterns — Singleton, Factory Method, Builder, Adapter, Decorator, Composite, Observer, Strategy, Command.',
    },
    {
      id: 'cert-spring-boot',
      title: 'Spring Boot REST API with Java & Gradle',
      issuer: 'CodeSignal',
      date: 'May 2026',
      verifyUrl: 'https://codesignal.com/learn/certificates/cmi5b4a3k003kjy04h90j6fip/course-paths/107',
      description:
        'Spring Core, Dependency Injection, REST Controllers, Spring Data JPA, entity relationships, pagination & sorting.',
    },
  ],
  contact: {
    email: 'thinhvt99@gmail.com',
    phone: '+1 (647) 515-7345',
    github: 'https://github.com/tvtrvn',
    linkedin: 'https://www.linkedin.com/in/thinh-tran111/',
  },
  resume: {
    fileName: 'resume.pdf',
    summary: [
      'B.A. Computer Science (Honours), Co-op · York University · Sep 2024 – Expected 2027.',
      'Learning Technology & AI Enablement Intern at Groupe Bel Canada (Jul 2026 – Present): 30+ SCORM e-learning packages, including 18 capability courses live on the corporate LMS, and a Power BI learning-engagement report (72 DAX measures) used by the team.',
      "Full-stack developer shipping production web apps end-to-end — sole developer of Pho Ginger's live ordering platform and owner of Swimingo's Florida-expansion web workstream (14 Florida pages across 6 merged pull requests).",
      'Builds with Claude Code agent teams: designs and directs the work, with separate validator agents checking it before it ships.',
      'Strong testing instincts — 76 backend tests on the Historical Trade Simulator, a 22-test Playwright end-to-end suite on Pho Ginger, JUnit on Java work.',
      'CodeSignal-certified: Mastering Design Patterns with Java (Apr 2026), Spring Boot REST API with Java & Gradle (May 2026).',
      'Languages: TypeScript, JavaScript, Python, Java, C / C++, C# (Basic), SQL, DAX, HTML / CSS. Spoken: English (native), French (fluent), Vietnamese (advanced).',
    ],
  },
  seo: {
    title: 'Thinh Tran — Full-Stack Developer & CS Student',
    description:
      'Portfolio of Thinh Tran. Full-stack web, AI-agent automation, e-learning technology, analytics, mobile, and developer tools. B.A. Computer Science (Honours), Co-op at York University, expected 2027.',
  },
};
